---

- include: network_init.yml

- include: >
    nic_config.yml
    nic_config_tmpl={{ item.nic_config_tmpl }}
    nic_name={{ item.nic_name }}
    nic_ip={{ item.nic_ip }}
    nic_netmask={{ item.nic_netmask }}
    nic_gateway={{ item.nic_gateway }}
    nic_dns={{ item.nic_dns }}
  with_items:
    - "{{ os_node_nic_list }}"

- include: package.yml
- include: package_config.yml

- name: update
  apt:
    update_cache: yes
  become: yes
  become_method: sudo

- name: upgrade
  apt:
    upgrade: dist
  become: yes
  become_method: sudo

- name: reboot remote host
  shell: shutdown -r now "Ansible update triggers rebootting..."
  become: yes
  become_method: sudo

- name: wait {{ reboot_time }} seconds for {{ ansible_host }} reboot
  local_action:
    module: wait_for
    port: "{{ ssh_port }}"
    search_regex: OpenSSH
    host: "{{ ansible_host }}"
    delay: "{{ reboot_time }}"

- name: install openstack client
  apt:
    name: python-openstackclient
  become: yes
  become_method: sudo

...

