---

- name: remove 127.0.1.1 in /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '127\.0\.1\.1.*'
    state: absent
  become: yes
  become_method: sudo

- name: add host to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: "{{ item.os_node }}\n"
    line: "{{ item.os_node_ip }}   {{ item.os_node }}"
  with_items:
    - "{{ os_node_list }}"
  become: yes
  become_method: sudo

- name: copy default network interface config file
  copy:
    src: network/interfaces
    dest: /etc/network/interfaces
    backup: yes
    owner: root
    group: root
    mode: 0644
  become: yes
  become_method: sudo

...
