---

- name: install NTP service
  apt:
    name: chrony
  become: yes
  become_method: sudo

- name: install software-properties-common
  apt:
    name: software-properties-common
  become: yes
  become_method: sudo

- name: add openstack repository
  shell: add-apt-repository cloud-archive:{{ os_version }}
  become: yes
  become_method: sudo

...

