---

#####
##### Installation
#####

- name: install mariadb-server, python-pymysql, python-mysqldb
  apt:
    name: "{{ item }}"
  with_items:
    - mariadb-server
    - python-pymysql
    - python-mysqldb
  become: yes
  become_method: sudo


#####
##### Configuration
#####

- name: configure mariadb
  ini_file: >
    dest=/etc/mysql/conf.d/mysqld_openstack.cnf
    section="{{ item.section }}"
    option="{{ item.option }}"
    value="{{ item.value }}"
    backup=yes
  become: yes
  become_method: sudo
  with_items:
    - section: mysqld
      option: bind-address
      value: "{{ manage_ip }}"
    - section: mysqld
      option: default-storage-engine
      value: innodb

- name: configure mariadb
  lineinfile:
    dest: /etc/mysql/conf.d/mysqld_openstack.cnf
    line: "innodb_file_per_table"
  become: yes
  become_method: sudo

- name: configure mariadb
  ini_file: >
    dest=/etc/mysql/conf.d/mysqld_openstack.cnf
    section="{{ item.section }}"
    option="{{ item.option }}"
    value="{{ item.value }}"
    backup=yes
  become: yes
  become_method: sudo
  with_items:
    - section: mysqld
      option: collation-server
      value: utf8_general_ci
    - section: mysqld
      option: init-connect
      value: "'SET NAMES utf8'"
    - section: mysqld
      option: character-set-server
      value: utf8
  notify:
    - restart mysql

- name: mysql_secure_installation - set root password
  mysql_user:
    host: "{{ item }}"
    name: root
    password: "{{ mysql_root_password }}"
    login_user: root
    login_password: "{{ mysql_root_password }}"
    check_implicit_admin: yes
  with_items:
    - localhost
    - 127.0.0.1
    - ::1

- name: mysql_secure_installation - remove anonymous users
  shell: mysql -u root --password={{ mysql_root_password }} -ne "{{ item }}"
  with_items:
    - DELETE FROM mysql.user WHERE User=''

- name: mysql_secure_installation - disallow root login remotely
  shell: mysql -u root --password={{ mysql_root_password }} -ne "{{ item }}"
  with_items:
    - DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')

- name: mysql_secure_installation - remove test database
  mysql_db:
    name: test
    login_user: root
    login_password: "{{ mysql_root_password }}"
    state: absent

- name: mysql_secure_installation - remove test database and access to it
  shell: mysql -u root --password={{ mysql_root_password }} -ne "{{ item }}"
  with_items:
    - DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%'

- name: mysql_secure_installation - reload privilege tables
  shell: mysql -u root --password={{ mysql_root_password }} -ne "{{ item }}"
  with_items:
    - FLUSH PRIVILEGES

...

